name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: packages/app/src-tauri

      - name: Install node dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Frontend tests
        run: npm run test

      - name: Cargo build
        run: cargo build --verbose
        working-directory: packages/app/src-tauri

      - name: Cargo test
        run: cargo test --verbose
        working-directory: packages/app/src-tauri
